### ISSUE TITLE
[Kubik|Product] Timeout errors on AWS S3

### ISSUE THREAD

**Issue by daniellavoie** [daniellavoie/kubik#30]
After some times, the ProductImageService throws the following exceptions.

```
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:230)
        at org.apache.http.impl.conn.PoolingClientConnectionManager$1.getConnection(PoolingClientConnectionManager.java:199)
        at sun.reflect.GeneratedMethodAccessor477.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.amazonaws.http.conn.ClientConnectionRequestFactory$Handler.invoke(ClientConnectionRequestFactory.java:70)
        at com.amazonaws.http.conn.$Proxy176.getConnection(Unknown Source)
        at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:424)
        at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:884)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
        at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:647)
        at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:441)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:292)
        at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3655)
        at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1132)
        at com.cspinformatique.kubik.server.domain.product.service.impl.ProductImageServiceImpl.loadInputStream(ProductImageServiceImpl.java:101)
        at com.cspinformatique.kubik.server.domain.product.controller.ProductController.loadProductImage(ProductController.java:250)
```

HttpClient might not be freed properly.

**Comment by daniellavoie** [comment]
Issue still present.
